FlaskServer/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Titie', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

    def append_content(self, old_content, user_input, bot_output):
        return old_content + '\n' + 'You: ' + user_input + '\n' + 'Harry Potter Bot:' +bot_output

FlaskServer/main/routes.py
from flask import render_template, request, Blueprint
from FlaskServer.model import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    #使用Post.query.paginate方法给posts分页
    #使用时间排序posts，让新发表的在最上面
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5)
    return render_template('home.html', posts=posts)

@main.route('/about')
def about():
    return render_template('about.html')

FlaskServer/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort,Blueprint
from flask_login import current_user, login_required
from FlaskServer import db
from FlaskServer.model import Post
from FlaskServer.posts.forms import PostForm
from FlaskServer.chatbot.chat import Bot

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content='You: ' + form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created.', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

#创建包含变量的route，代表不同的post，post_id是数据库自动加上的int，因为它是primaryKey
#post.html展示一个post的内容，需要在home的template中加上post的link
@posts.route("/post/<int:post_id>")
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        #update Post内容，不添加新内容就不用使用add方法
        bot = Bot(0)
        bot.wakeup()
        bot_response = bot.send_message(form.content.data)
        if bot_response == 'BotError':
            flash('NOTICE: There might be an error on the bot. Please contact the administator: zli18876@gmail.com', 'danger')
        elif bot_response == 'OtherError':
            flash('NOTICE: Please wait a minute and try again. If you still get a NOTICE, Please contact the administator: zli18876@gmail.com', 'info')
        else:
            post.title = form.title.data
            post.content = form.append_content(post.content, form.content.data, bot_response)
            db.session.commit()
            #flash('Your post has been updated!', 'success')
            return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        #用户先GET请求到update这个页面，之后填完表之后POST上交，第一次GET
        #的时候把当前的内容显示进去
        #显示当前的Post内容，和修改用户信息那里一样
        form.title.data = post.title
        #form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

#按下delete确定按钮之后，向这个方法发送POST方法，包含post_id
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

FlaskServer/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from FlaskServer import db
from werkzeug import security
from FlaskServer.model import User, Post
from FlaskServer.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, 
                                    RequestResetForm, ResetPasswordForm)
from FlaskServer.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        #返回hash后的password字符串
        hashed_password = security.generate_password_hash(form.password.data)
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        #防止用户注册时使用已经存在的用户名和邮箱，因为这两项已经标注了不可重复在数据库里
        #所以添加重复用户的时候数据库会报错，需要处理一下，较好的处理方式是在forms文件里
        #定义自己的validation规则防止重复，这样可以轻松展示出哪里有问题
        db.session.add(user)
        db.session.commit()
        
        #需要更新layout.html来让flash信息能够出现在任何界面上
        flash(f'Account created for {form.username.data}! You are now able to log in', 'success')
        #使用url_for找到当前文件的home函数，之后redirect到home页面
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        #如果User存在并且数据库中password的hash可以对应到输入的password，则登录
        if user and security.check_password_hash(user.password, form.password.data):
            login_user(user, form.remember.data)
            #登录后尝试获取next参数，代表用户接下来想访问的页面，如果没有返回None（使用get方法）
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    #由于调用这个函数的就是要logout的user所以不需要传参
    logout_user()
    return redirect(url_for('main.home'))

#account界面只有登录之后才能看到，学习如何限制页面访问
@users.route("/account", methods=['GET', 'POST'])
#现在LoginManager知道需要login才能访问account，但是还需要告诉它login页面的route是什么
@login_required
def account():
    form = UpdateAccountForm()
    #使用post请求
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        #这里相当于update了数据库，所以需要commit
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    #使用get请求，并且默认在form里填入当前的username和email
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    #数据库中当前用户的image_file时有默认值的，所以一定能取得一个图片
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


#展示某个User的所有Post
@users.route("/user/<string:username>")
def user_post(username):
    #使用Post.query.paginate方法给posts分页
    #使用时间排序posts，让新发表的在最上面
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(per_page=5)
    return render_template('user_post.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    #确保在reset password之前已经logout
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your Password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    #确保在reset password之前已经logout
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        #返回hash后的password字符串
        hashed_password = security.generate_password_hash(form.password.data)
        #防止用户注册时使用已经存在的用户名和邮箱，因为这两项已经标注了不可重复在数据库里
        #所以添加重复用户的时候数据库会报错，需要处理一下，较好的处理方式是在forms文件里
        #定义自己的validation规则防止重复，这样可以轻松展示出哪里有问题
        user.password = hashed_password
        db.session.commit()
        
        #需要更新layout.html来让flash信息能够出现在任何界面上
        flash(f'Password updated for {form.username.data}! You are now able to log in', 'success')
        #使用url_for找到当前文件的home函数，之后redirect到home页面
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

FlaskServer/templates/about.html
{%extends "layout.html"%}
{%block content%}
    <h1>About Page</h1>
{%endblock content%}

FlaskServer/templates/account.html
{%extends "layout.html"%}
{%block content%}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src={{ image_file }}>
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <div class="content_section">
            <!--enctype="multipart/form-data"一定要写，因为form中有图片上传也有文字-->
            <form method="POST" action="" enctype="multipart/form-data">
                    {{form.hidden_tag()}}
                    <fieldset class="form-group">
                        <legend class="border-bottom md-4">
                            Account Info
                        </legend>
                        <div class="from-group">
                            {{form.username.label(class="from-control-label")}}
                            {% if form.username.errors %}
                                {{form.username.label(class="from-control from-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>
                                            {{ error }}
                                        </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{form.username(class="from-control from-control-lg")}}
                            {% endif %}
                        </div>
                        <div class="from-group">
                            {{form.email.label(class="from-control-label")}}
                            {% if form.email.errors %}
                                {{form.email.label(class="from-control from-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>
                                            {{ error }}
                                        </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{form.email(class="from-control from-control-lg")}}
                            {% endif %}
                        </div>
                        <div class="from-group">
                            {{form.picture.label(class="from-control-label")}}
                            {{ form.picture(class="form-control-file") }}
                            {% if form.picture.errors %}
                                {% for error in form.picture.errors %}
                                    <span class="text-danger">
                                        {{ error }}
                                    </span>
                                    </br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{form.submit(class="btn btn-outline-info")}}
                    </div>
            </form>
        </div>
    </div>
{%endblock content%}

FlaskServer/templates/create_post.html
{%extends "layout.html"%}
{%block content%}
<div class="content_section">
    <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="border-bottom md-4">
                    {{ legend }}
                </legend>
                <div class="from-group">
                    {{form.title.label(class="from-control-label")}}
                    {% if form.title.errors %}
                        {{form.title.label(class="from-control from-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.title(class="from-control from-control-lg")}}
                    {% endif %}
                </div>
                <div class="from-group">
                    {{form.content.label(class="from-control-label")}}
                    {% if form.content.errors %}
                        {{form.content.label(class="from-control from-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.content(class="from-control from-control-lg")}}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
    </form>
</div>
{%endblock content%}

FlaskServer/templates/home.html
{% extends "layout.html" %}
{%block content%}
<!--因为现在posts为paginate的返回值，所以使用posts.items-->
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"></img>
            <div class="media-body">
            <div class="article-metadata">
                <!--找到post函数，并且参数为post.id-->
                <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d, %H:%M:%S") }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    <!--这里是要做出显示当前页的附近几页和首尾的几页的效果，iter_pages函数可以帮我们完成-->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{%endblock content%}

FlaskServer/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" type="text/css">
        {% if title %}
            <title>Flask Blog - {{ title }}</title>
        {% else %}
            <title>Flask Blog</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
              <div class="container">
                <a class="navbar-brand mr-4" href="/">Bot Chat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                  <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                    <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
                  </div>
                  <!-- Navbar Right Side -->
                  <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                      <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">New Chat</a>
                      <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                      <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                      
                    {% else %}
                      <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                      <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </nav>
          </header>

        <main role="main" class="container">
            <div class="row">
                <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-4">
                    <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                        <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                    </div>
                </div>
            </div>
        </main>
        
        <!-- Option 2: Separate Popper and Bootstrap JS -->
        
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        
    </body>
</html>

FlaskServer/templates/login.html
{%extends "layout.html"%}
{%block content%}
    <div class="content_section">
        <form method="POST" action="">
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class="border-bottom md-4">
                        Log in
                    </legend>
                    <div class="from-group">
                        {{form.email.label(class="from-control-label")}}
                        {% if form.email.errors %}
                            {{form.email.label(class="from-control from-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.email(class="from-control from-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="from-group">
                        {{form.password.label(class="from-control-label")}}
                        {% if form.password.errors %}
                            {{form.password.label(class="from-control from-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.password(class="from-control from-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember(class="form-check-lable") }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{form.submit(class="btn btn-outline-info")}}
                </div>
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
        </form>
    </div>
    <div class="boder-top pt-3">
        <small class="text-muted">
            Need a account? <a class="ml-2" href="{{url_for('users.register')}}">Sign up now</a>
        </small>
    </div>
{%endblock content%}

FlaskServer/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Send Message</a>
            <!--注意，delete点击后无法弹出Modal-->
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete history</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      {% for line in post.content.split('\n') %}
        {% if line.startswith('You') %}
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        {% else %}
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='bot_icon/' + 'HarryPotter.png') }}">
        {% endif %}
        <p class="article-content">{{ line }}</p>
      {% endfor %}
      <!--<p class="article-content">{{ post.content }}</p>-->
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <!--可以在这里用div填写modal小介面中显示的文字，但是这里不需要-->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

FlaskServer/templates/reset_request.html
{%extends "layout.html"%}
{%block content%}
    <div class="content_section">
        <form method="POST" action="">
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class="border-bottom md-4">
                        Reset Password
                    </legend>
                    <div class="from-group">
                        {{form.email.label(class="from-control-label")}}
                        {% if form.email.errors %}
                            {{form.email.label(class="from-control from-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.email(class="from-control from-control-lg")}}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{form.submit(class="btn btn-outline-info")}}
                </div>
        </form>
    </div>
{%endblock content%}

FlaskServer/templates/reset_token.html
{%extends "layout.html"%}
{%block content%}
    <div class="content_section">
        <form method="POST" action="">
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class="border-bottom md-4">
                        Reset Password
                    </legend>
                    <div class="from-group">
                        {{form.password.label(class="from-control-label")}}
                        {% if form.password.errors %}
                            {{form.password.label(class="from-control from-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.password(class="from-control from-control-lg")}}
                        {% endif %}
                    </div>
                    <div class="from-group">
                        {{form.confirm_password.label(class="from-control-label")}}
                        {% if form.confirm_password.errors %}
                            {{form.confirm_password.label(class="from-control from-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.confirm_password(class="from-control from-control-lg")}}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{form.submit(class="btn btn-outline-info")}}
                </div>
        </form>
    </div>
{%endblock content%}

FlaskServer/templates/user_post.html
{% extends "layout.html" %}
{%block content%}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
<!--因为现在posts为paginate的返回值，所以使用posts.items-->
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"></img>
            <div class="media-body">
            <div class="article-metadata">
                <!--找到post函数，并且参数为post.id-->
                <a class="mr-2" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d, %H:%M:%S") }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    <!--这里是要做出显示当前页的附近几页和首尾的几页的效果，iter_pages函数可以帮我们完成-->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_post', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_post', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{%endblock content%}